[package]
name = "meilisearch-types"
publish = false

version.workspace = true
authors.workspace = true
description.workspace = true
homepage.workspace = true
readme.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
actix-web = { version = "4.2.1", default-features = false }
anyhow = "1.0.65"
bincode = { version = "2.0.0-rc.2", features = ["serde"] }
convert_case = "0.6.0"
csv = "1.1.6"
deserr = "0.5.0"
either = { version = "1.6.1", features = ["serde"] }
enum-iterator = "1.1.3"
file-store = { path = "../file-store" }
flate2 = "1.0.24"
fst = "0.4.7"
memmap2 = "0.5.7"
milli = { path = "../milli", default-features = false }
roaring = { version = "0.10.0", features = ["serde"] }
serde = { version = "1.0.145", features = ["derive"] }
serde-cs = "0.2.4"
serde_json = "1.0.85"
tar = "0.4.38"
tempfile = "3.3.0"
thiserror = "1.0.30"
time = { version = "0.3.20", git = "https://github.com/irevoire/time", branch = "bincode-support", features = ["serde-well-known", "formatting", "parsing", "macros", "bincode"] }
tokio = "1.24"
uuid = { version = "1.1.2", features = ["serde", "v4"] }

[dev-dependencies]
insta = "1.19.1"
meili-snap = { path = "../meili-snap" }

[features]
# all specialized tokenizations
default = ["milli/default"]

# chinese specialized tokenization
chinese = ["milli/chinese"]
# hebrew specialized tokenization
hebrew = ["milli/hebrew"]
# japanese specialized tokenization
japanese = ["milli/japanese"]
# thai specialized tokenization
thai = ["milli/thai"]
